name = "New Morning: Catastrophe"
version = "0.3.0-alpha.8-sl-packet-fix"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b39b736227e13ebc1e4f9be4c0ca9e0d52d80e511e6208ba3ce2dff476b6a137"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
