name = "New Morning: Catastrophe"
version = "0.3.0-alpha.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f7662e76416f193dba13ee1cf6314d65647a2c1e9cbbe417ae6f209003c23e3f"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
