name = "New Morning: Catastrophe"
version = "0.3.0-alpha.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "42d6805334222e16cbe2aa3eb4dc0175665fdbfc28454cf01fe0f17f058f6ec9"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
