name = "New Morning: Catastrophe"
version = "0.3.0-alpha.14"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a8ba16f4734417e6fe78fa12a5d4d88fa0b557daa08846b4af8a0c566ac88cb3"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
