name = "New Morning: Catastrophe"
version = "0.3.0-alpha.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "14e488fa04a949f4625eeae9112bf6cfcf11647b4e6f4dcfcca0610862d658bf"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
