name = "New Morning: Catastrophe"
version = "0.3.0-alpha.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e783506266d7da300ca8ea8e3008b501cba4f0fb610bab7b7011363ab45e0530"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
